language: node_js

node_js:
- 6
- stable

before_install:
- >
  if [ "$TRAVIS_NODE_VERSION" = "6" ]; then
    yarn upgrade prettier@1.19.1
  fi

script:
- yarn run lint
- yarn run build
- yarn run test

after_script:
- node_modules/.bin/codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
