language: node_js

node_js:
- 6
- stable

script:
- yarn run lint
- yarn run build
- yarn run test
# yarn does not work on node 4
- if [ "$TRAVIS_NODE_VERSION" = "6" ]; then nvm install 4; fi
- if [ "$TRAVIS_NODE_VERSION" = "6" ]; then npm run test; fi

after_script:
- yarn codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
