language: node_js

node_js:
- 4
- 6
- stable

script:
- yarn run lint
- yarn run build
- yarn run test

after_script:
- yarn codecov

cache:
  yarn: true
  directories:
  - node_modules

matrix:
  fast_finish: true
